name: build

on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Build LaTeX
        uses: dante-ev/latex-action@2021-A
        with:
          # The root LaTeX file to be compiled
          root_file: book.tex
          # The working directory for the latex compiler to be invoked
          working_directory: book/
          # Extra arguments to be passed to the latex compiler
          args: -xelatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: book
          path: book/book.pdf
          if-no-files-found: error
