name: build

on:
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Tectonic Cache
        uses: actions/cache@v3
        with:
          path: ~/.cache/Tectonic
          key: ${{ runner.os }}-tectonic-${{ hashFiles('**/*.tex') }}
          restore-keys: |
           ${{ runner.os }}-tectonic-

      - name: Init Tectonic
        uses: wtfjoke/setup-tectonic@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          tectonic-version: 0.9.0
          biber-version: 2.16

      - name: Run Tectonic
        run: tectonic book/book.tex

      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: book
          path: book/book.pdf
          if-no-files-found: error
