name: build

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Build LaTeX
        uses: dante-ev/latex-action@2021-A
        with:
          root_file: book.tex
          working_directory: book/
          compiler: latexmk
          args: -xelatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode

      - name: Upload a PDF Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: book
          path: book/book.pdf
          if-no-files-found: error
