name: release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Build LaTeX
        uses: dante-ev/latex-action@2021-A
        with:
          root_file: book.tex
          working_directory: book/
          compiler: latexmk
          args: -xelatex -latexoption=-file-line-error -latexoption=-interaction=nonstopmode

      - name: Get Version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

      - name: Name the Book
        run: |
          mv book/book.pdf book/ShangshouCMake-${{ steps.get_version.outputs.VERSION }}.pdf

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: book/ShangshouCMake-*.pdf
